controller:
  runAsUser: 0
  podSecurityContextOverride:
    runAsUser: 0
    runAsNonRoot: false
  containerSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true

  jenkinsUrl: https://jenkins.hanjun.site

persistence:
  existingClaim: jenkins-pvc  # 기존 PVC 사용

